# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb7b1abf92859b3a9972de0429a57c5b469a7390f2e6cc6e651389b3e54b971cf24fb0e1b93646edd2d276dc6392bf7a94ea2abb2561e79cf2321cedc223ad9

test:
  secret_key_base: 4ed2a38ae4df45498becd05292b109013c057bd42b8300213d0cc90cf9140b183b36e5937e0a058fa62f285294dc882599675dc8314a539fe75462fd8e152b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
